### PR TITLE
New printer interface...

### PR DESCRIPTION
**Pull request by treepleks**
Luc,

I adapted the  Smoothieware web server interface to the context of the web server code in the ESP.
Have a look to the last commit 6cad3a7.

The previous one is also probably what I intended to do initially on the "strcat". Microscopic change :-)

T.

### CODE REVIEW

**Comment by luc-github** [comment]
>what I intended to do initially on the "strcat". Microscopic change

Yes strcpy moving pointer is an elegant way to work around, nice refactoring

>I adapted the Smoothieware web server interface to the context of the web server code in the ESP.

From SVG/JS syntax point of view ? or from UI point of view ?

**Comment by treepleks** [comment]
Le 23/01/2016 16:42, Luc a écrit :
>
>     what I intended to do initially on the "strcat". Microscopic change
>
> Yes strcpy moving pointer is an elegant way to work around, nice
> refactoring
>
>     I adapted the Smoothieware web server interface to the context of
>     the web server code in the ESP.
>
> From SVG/JS syntax point of view ? or from UI point of view ?
>
The JS code is essentially unchanged. It's the UI.

I just grabbed the SVG from Smoothieware web server for the X/Y/Z
control (that mimics the Pronterface look), removed all SMIL animations
from it and replaced by CSS ones using .hover and used the same SVG for
Extruder control.

**Comment by luc-github** [comment]
Very nice UI indeed - great job - the pronterface looks is definitely great - should a reference to original author also be mentioned somewhere or you did all by yourself ? 

one comment : IMHO web interface primary usage is not Jog ( unlike connected software) neither launch print but follow print status / adjust temp/speed, it is more a remote tool, so I am not sure Jog should be the first item to display on UI but I think should be print status or temperatures, just my 2 cents

Also I think doing some adjustment to allow to change axis representation would be great to match user printer orientation. for example current one is totally upside down for davinci printers and I got this feedback on first UI I did where I did not pay attention to it, just sharing user feedback.

Software allows to switch axis - I think web UI should allow it also, and the way you did should allow this easily  - what do you think ?

Great job again!

**Comment by treepleks** [comment]
Le 24/01/2016 06:04, Luc a écrit :
>
> Very nice UI indeed - great job - the pronterface looks is definitely
> great - should a reference to original author also be mentioned
> somewhere or you did all by yourself ?
>
A reference to Smoothieware web interface should be inserted. The
original author is Jim Morris https://github.com/wolfmanjm (I sent him a
mail telling him a version w/o SLIM animations was available). My action
was limited to adding "visibility" control, inserting correct JS calls
and replacing SLIM animations (that did not work very well on Chrome
beside being obsolete) by CSS hover animations (which was not as easy as
I thought, I'm a complete AJAX newbie).
>
> one comment : IMHO web interface primary usage is not Jog ( unlike
> connected software) neither launch print but follow print status /
> adjust temp/speed, it is more a remote tool, so I am not sure Jog
> should be the first item to display on UI but I think should be print
> status or temperatures, just my 2 cents
>
Yes. It makes sense. Please, move things around as you like. I'm not
using this already (my printer still not there, the steel frame making
is taking more time than expected).
>
> Also I think doing some adjustment to allow to change axis
> representation would be great to match user printer orientation. for
> example current one is totally upside down for davinci printers and I
> got this feedback on first UI I did where I did not pay attention to
> it, just sharing user feedback.
>
> Software allows to switch axis - I think web UI should allow it also,
> and the way you did should allow this easily - what do you think ?
>
What do you mean by "switching axis" exactly ?

> Great job again!
>
Kudos to wolfmanmj :-)

Thomas

**Comment by luc-github** [comment]
Thanks for the link I will embeded it in code and may read me - you are in readme and commits

>What do you mean by "switching axis" exactly ?
For example:
Z+ is currently up
Z- is currently down
This is ok for a delta or a prussa but this is not the reality for all printers like davinci which have bed going down.
So Z- should be up and Z+ should be down
same for X and Y
But as is not easy to cover all configuration it is better to allow user to flip/switch orientation with just a check box in settings like in repetier or may be pronterface.

**Comment by luc-github** [comment]
I have sent email to Jim to ask him if there is no issue to integrate the UI

**Comment by wolfmanjm** [comment]
Smoothieware is licensed GPL, so long as you maintain that license it is ok to use this.

**Comment by luc-github** [comment]
It is the case - thanks a lot ^_^

**Comment by luc-github** [comment]
as imrahil  UI is available I think the PR can be closed

**Pull request closed without merging**
