### PR TITLE
Web redesign

### PR DESCRIPTION
**Pull request by VitaliyAndreevich**
fix printer file names with spaces
improove restaring scripts.
fix printer.html markup
replace printer.tpl by printer.html
replace home.tpl by home.html
web interface: move menu to index.html
move printer javascript to separate file
move css styles to separate files. Add cache for it.

### CODE REVIEW

**Comment by luc-github** [comment]
looks big changes, I did not test it yet but I have some questions:
* Are you able to quantify the gain of performances of these changes ?

also now server need to handle more files to display one page server request response may decrease 
- what is the impact on navigation on AP mode which by design get lot of requests ? 
- what is the impact using tcp access in same time as web accesss ?

**Comment by VitaliyAndreevich** [comment]
Currently I can make some mesures of performances for client mode only

**Comment by VitaliyAndreevich** [comment]
image

**Comment by luc-github** [comment]
what tool do you use ? I use  page load time and got 412ms of response time for current FWfor access point page
image

**Comment by VitaliyAndreevich** [comment]
I am using chrome buildin dev tool. My messure includes connecting + request + response. Maybe we have messure difference becouse of using different hardware (router)

**Comment by luc-github** [comment]
Using dev tools - I got 500ms, yes this means these measurement of gain are not really relevant 
image

**Comment by luc-github** [comment]
UI has been fully rewriten not using template  https://github.com/luc-github/ESP3D-WEBUI
Performance is not proven to be better in either case, but due to new FW and UI this PR ccannot be implemented

**Pull request closed without merging**
