### PR TITLE
Fix char* to uin8_t* conversion issue

### PR DESCRIPTION
**Pull request by G-Pereira**
Fixed code related to OLED display

### CODE REVIEW

**Comment by luc-github** [comment]
Your issue is due to the fact that you use another version than the one present in libraries directory

**Comment by luc-github** [comment]
I cannot test all libraries update and the possible side effect that is why I froze the versions

**Comment by G-Pereira** [comment]
I didn't see that. You can either close this or update the version of the library since I've tested it and it works fine

**Comment by luc-github** [comment]
I won't change anything for 2.1.

But I keep PR as reminder to update lib for/in 3.0 as it is still in early development stage

**Comment by G-Pereira** [comment]
Seems a good idea

**Comment by luc-github** [comment]
fixed in 3.0 thanks for pointing out

**Pull request closed without merging**
